/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as WorkspaceReportsRouteImport } from './routes/workspace/reports'
import { Route as WorkspaceOverviewRouteImport } from './routes/workspace/overview'
import { Route as WorkspaceInventoryRouteImport } from './routes/workspace/inventory'
import { Route as WorkspaceAnalyticsRouteImport } from './routes/workspace/analytics'
import { Route as WorkspaceAcquisitionsRouteImport } from './routes/workspace/acquisitions'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout/payment'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DevComponentsRouteImport } from './routes/_dev/components'
import { Route as CCategoryIndexRouteImport } from './routes/c/$category/index'
import { Route as CCategoryPSlugRouteImport } from './routes/c/$category/p/$slug'

const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceReportsRoute = WorkspaceReportsRouteImport.update({
  id: '/workspace/reports',
  path: '/workspace/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceOverviewRoute = WorkspaceOverviewRouteImport.update({
  id: '/workspace/overview',
  path: '/workspace/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceInventoryRoute = WorkspaceInventoryRouteImport.update({
  id: '/workspace/inventory',
  path: '/workspace/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAnalyticsRoute = WorkspaceAnalyticsRouteImport.update({
  id: '/workspace/analytics',
  path: '/workspace/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAcquisitionsRoute = WorkspaceAcquisitionsRouteImport.update({
  id: '/workspace/acquisitions',
  path: '/workspace/acquisitions',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/checkout/payment',
  path: '/checkout/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/_dev/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryIndexRoute = CCategoryIndexRouteImport.update({
  id: '/c/$category/',
  path: '/c/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryPSlugRoute = CCategoryPSlugRouteImport.update({
  id: '/c/$category/p/$slug',
  path: '/c/$category/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/components': typeof DevComponentsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/workspace/acquisitions': typeof WorkspaceAcquisitionsRoute
  '/workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/workspace/inventory': typeof WorkspaceInventoryRoute
  '/workspace/overview': typeof WorkspaceOverviewRoute
  '/workspace/reports': typeof WorkspaceReportsRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/c/$category/': typeof CCategoryIndexRoute
  '/c/$category/p/$slug': typeof CCategoryPSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/components': typeof DevComponentsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/workspace/acquisitions': typeof WorkspaceAcquisitionsRoute
  '/workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/workspace/inventory': typeof WorkspaceInventoryRoute
  '/workspace/overview': typeof WorkspaceOverviewRoute
  '/workspace/reports': typeof WorkspaceReportsRoute
  '/checkout': typeof CheckoutIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/c/$category': typeof CCategoryIndexRoute
  '/c/$category/p/$slug': typeof CCategoryPSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/_dev/components': typeof DevComponentsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/workspace/acquisitions': typeof WorkspaceAcquisitionsRoute
  '/workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/workspace/inventory': typeof WorkspaceInventoryRoute
  '/workspace/overview': typeof WorkspaceOverviewRoute
  '/workspace/reports': typeof WorkspaceReportsRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/c/$category/': typeof CCategoryIndexRoute
  '/c/$category/p/$slug': typeof CCategoryPSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/components'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/checkout/payment'
    | '/orders/$orderId'
    | '/workspace/acquisitions'
    | '/workspace/analytics'
    | '/workspace/inventory'
    | '/workspace/overview'
    | '/workspace/reports'
    | '/checkout/'
    | '/workspace/'
    | '/c/$category/'
    | '/c/$category/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/components'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/checkout/payment'
    | '/orders/$orderId'
    | '/workspace/acquisitions'
    | '/workspace/analytics'
    | '/workspace/inventory'
    | '/workspace/overview'
    | '/workspace/reports'
    | '/checkout'
    | '/workspace'
    | '/c/$category'
    | '/c/$category/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/_dev/components'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/checkout/payment'
    | '/orders/$orderId'
    | '/workspace/acquisitions'
    | '/workspace/analytics'
    | '/workspace/inventory'
    | '/workspace/overview'
    | '/workspace/reports'
    | '/checkout/'
    | '/workspace/'
    | '/c/$category/'
    | '/c/$category/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  DevComponentsRoute: typeof DevComponentsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetRoute: typeof AuthResetRoute
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  WorkspaceAcquisitionsRoute: typeof WorkspaceAcquisitionsRoute
  WorkspaceAnalyticsRoute: typeof WorkspaceAnalyticsRoute
  WorkspaceInventoryRoute: typeof WorkspaceInventoryRoute
  WorkspaceOverviewRoute: typeof WorkspaceOverviewRoute
  WorkspaceReportsRoute: typeof WorkspaceReportsRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  CCategoryIndexRoute: typeof CCategoryIndexRoute
  CCategoryPSlugRoute: typeof CCategoryPSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/reports': {
      id: '/workspace/reports'
      path: '/workspace/reports'
      fullPath: '/workspace/reports'
      preLoaderRoute: typeof WorkspaceReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/overview': {
      id: '/workspace/overview'
      path: '/workspace/overview'
      fullPath: '/workspace/overview'
      preLoaderRoute: typeof WorkspaceOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/inventory': {
      id: '/workspace/inventory'
      path: '/workspace/inventory'
      fullPath: '/workspace/inventory'
      preLoaderRoute: typeof WorkspaceInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/analytics': {
      id: '/workspace/analytics'
      path: '/workspace/analytics'
      fullPath: '/workspace/analytics'
      preLoaderRoute: typeof WorkspaceAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/acquisitions': {
      id: '/workspace/acquisitions'
      path: '/workspace/acquisitions'
      fullPath: '/workspace/acquisitions'
      preLoaderRoute: typeof WorkspaceAcquisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/checkout/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dev/components': {
      id: '/_dev/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$category/': {
      id: '/c/$category/'
      path: '/c/$category'
      fullPath: '/c/$category/'
      preLoaderRoute: typeof CCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$category/p/$slug': {
      id: '/c/$category/p/$slug'
      path: '/c/$category/p/$slug'
      fullPath: '/c/$category/p/$slug'
      preLoaderRoute: typeof CCategoryPSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  DevComponentsRoute: DevComponentsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetRoute: AuthResetRoute,
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  WorkspaceAcquisitionsRoute: WorkspaceAcquisitionsRoute,
  WorkspaceAnalyticsRoute: WorkspaceAnalyticsRoute,
  WorkspaceInventoryRoute: WorkspaceInventoryRoute,
  WorkspaceOverviewRoute: WorkspaceOverviewRoute,
  WorkspaceReportsRoute: WorkspaceReportsRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  CCategoryIndexRoute: CCategoryIndexRoute,
  CCategoryPSlugRoute: CCategoryPSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
