/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CartRouteImport } from './routes/cart'
import { Route as WorkspaceRouteRouteImport } from './routes/workspace/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as WorkspaceReportsRouteImport } from './routes/workspace/reports'
import { Route as WorkspaceOverviewRouteImport } from './routes/workspace/overview'
import { Route as WorkspaceInventoryRouteImport } from './routes/workspace/inventory'
import { Route as WorkspaceAnalyticsRouteImport } from './routes/workspace/analytics'
import { Route as WorkspaceAcquisitionsRouteImport } from './routes/workspace/acquisitions'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as CheckoutReviewRouteImport } from './routes/checkout/review'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout/payment'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as DevComponentsRouteImport } from './routes/_dev/components'
import { Route as CCategoryIndexRouteImport } from './routes/c/$category/index'
import { Route as CCategoryPSlugRouteImport } from './routes/c/$category/p/$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceReportsRoute = WorkspaceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceOverviewRoute = WorkspaceOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceInventoryRoute = WorkspaceInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAnalyticsRoute = WorkspaceAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAcquisitionsRoute = WorkspaceAcquisitionsRouteImport.update({
  id: '/acquisitions',
  path: '/acquisitions',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReviewRoute = CheckoutReviewRouteImport.update({
  id: '/checkout/review',
  path: '/checkout/review',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/checkout/payment',
  path: '/checkout/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRouteRoute,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/_dev/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryIndexRoute = CCategoryIndexRouteImport.update({
  id: '/c/$category/',
  path: '/c/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryPSlugRoute = CCategoryPSlugRouteImport.update({
  id: '/c/$category/p/$slug',
  path: '/c/$category/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/search': typeof SearchRoute
  '/components': typeof DevComponentsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/workspace/acquisitions': typeof WorkspaceAcquisitionsRoute
  '/workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/workspace/inventory': typeof WorkspaceInventoryRoute
  '/workspace/overview': typeof WorkspaceOverviewRoute
  '/workspace/reports': typeof WorkspaceReportsRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/c/$category/': typeof CCategoryIndexRoute
  '/c/$category/p/$slug': typeof CCategoryPSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/search': typeof SearchRoute
  '/components': typeof DevComponentsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/workspace/acquisitions': typeof WorkspaceAcquisitionsRoute
  '/workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/workspace/inventory': typeof WorkspaceInventoryRoute
  '/workspace/overview': typeof WorkspaceOverviewRoute
  '/workspace/reports': typeof WorkspaceReportsRoute
  '/checkout': typeof CheckoutIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/c/$category': typeof CCategoryIndexRoute
  '/c/$category/p/$slug': typeof CCategoryPSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/search': typeof SearchRoute
  '/_dev/components': typeof DevComponentsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/workspace/acquisitions': typeof WorkspaceAcquisitionsRoute
  '/workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/workspace/inventory': typeof WorkspaceInventoryRoute
  '/workspace/overview': typeof WorkspaceOverviewRoute
  '/workspace/reports': typeof WorkspaceReportsRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/c/$category/': typeof CCategoryIndexRoute
  '/c/$category/p/$slug': typeof CCategoryPSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/workspace'
    | '/cart'
    | '/search'
    | '/components'
    | '/account/orders'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/checkout/payment'
    | '/checkout/review'
    | '/orders/$orderId'
    | '/workspace/acquisitions'
    | '/workspace/analytics'
    | '/workspace/inventory'
    | '/workspace/overview'
    | '/workspace/reports'
    | '/checkout/'
    | '/workspace/'
    | '/c/$category/'
    | '/c/$category/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/search'
    | '/components'
    | '/account/orders'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/checkout/payment'
    | '/checkout/review'
    | '/orders/$orderId'
    | '/workspace/acquisitions'
    | '/workspace/analytics'
    | '/workspace/inventory'
    | '/workspace/overview'
    | '/workspace/reports'
    | '/checkout'
    | '/workspace'
    | '/c/$category'
    | '/c/$category/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/workspace'
    | '/cart'
    | '/search'
    | '/_dev/components'
    | '/account/orders'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/checkout/payment'
    | '/checkout/review'
    | '/orders/$orderId'
    | '/workspace/acquisitions'
    | '/workspace/analytics'
    | '/workspace/inventory'
    | '/workspace/overview'
    | '/workspace/reports'
    | '/checkout/'
    | '/workspace/'
    | '/c/$category/'
    | '/c/$category/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  CartRoute: typeof CartRoute
  SearchRoute: typeof SearchRoute
  DevComponentsRoute: typeof DevComponentsRoute
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutReviewRoute: typeof CheckoutReviewRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CCategoryIndexRoute: typeof CCategoryIndexRoute
  CCategoryPSlugRoute: typeof CCategoryPSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/reports': {
      id: '/workspace/reports'
      path: '/reports'
      fullPath: '/workspace/reports'
      preLoaderRoute: typeof WorkspaceReportsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/overview': {
      id: '/workspace/overview'
      path: '/overview'
      fullPath: '/workspace/overview'
      preLoaderRoute: typeof WorkspaceOverviewRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/inventory': {
      id: '/workspace/inventory'
      path: '/inventory'
      fullPath: '/workspace/inventory'
      preLoaderRoute: typeof WorkspaceInventoryRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/analytics': {
      id: '/workspace/analytics'
      path: '/analytics'
      fullPath: '/workspace/analytics'
      preLoaderRoute: typeof WorkspaceAnalyticsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/acquisitions': {
      id: '/workspace/acquisitions'
      path: '/acquisitions'
      fullPath: '/workspace/acquisitions'
      preLoaderRoute: typeof WorkspaceAcquisitionsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/review': {
      id: '/checkout/review'
      path: '/checkout/review'
      fullPath: '/checkout/review'
      preLoaderRoute: typeof CheckoutReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/checkout/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_dev/components': {
      id: '/_dev/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$category/': {
      id: '/c/$category/'
      path: '/c/$category'
      fullPath: '/c/$category/'
      preLoaderRoute: typeof CCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$category/p/$slug': {
      id: '/c/$category/p/$slug'
      path: '/c/$category/p/$slug'
      fullPath: '/c/$category/p/$slug'
      preLoaderRoute: typeof CCategoryPSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountOrdersRoute: AccountOrdersRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface WorkspaceRouteRouteChildren {
  WorkspaceAcquisitionsRoute: typeof WorkspaceAcquisitionsRoute
  WorkspaceAnalyticsRoute: typeof WorkspaceAnalyticsRoute
  WorkspaceInventoryRoute: typeof WorkspaceInventoryRoute
  WorkspaceOverviewRoute: typeof WorkspaceOverviewRoute
  WorkspaceReportsRoute: typeof WorkspaceReportsRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceAcquisitionsRoute: WorkspaceAcquisitionsRoute,
  WorkspaceAnalyticsRoute: WorkspaceAnalyticsRoute,
  WorkspaceInventoryRoute: WorkspaceInventoryRoute,
  WorkspaceOverviewRoute: WorkspaceOverviewRoute,
  WorkspaceReportsRoute: WorkspaceReportsRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  CartRoute: CartRoute,
  SearchRoute: SearchRoute,
  DevComponentsRoute: DevComponentsRoute,
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutReviewRoute: CheckoutReviewRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  CCategoryIndexRoute: CCategoryIndexRoute,
  CCategoryPSlugRoute: CCategoryPSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
